wget "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiO2ZjLgwtn_jUvX6XMykqyJQI-b25gHqgxus24L4n6gMaF-Fq6XDUtcNLJHQlY5h4w9kKcEyEF1Q1SLxyiwpGK3D8Ucuw6gZlrdBiPppmSWAjq88UHOuUDGAAVMJa1yJB_1nTy-q_7X6xx4EEk9SeQW22nZtBWuuWQ5Q6JeKPbqwZL4z1ibHl4l4J63Q/s16000/nova%20revista%20ebd.png" -O capa.png
wget "https://escolabiblicadominical.com.br/licao-01-as-sutilezas-de-satanas-contra-a-igreja-de-cristo/"  -O licao-01.html
wget "https://escolabiblicadominical.com.br/licao-02-a-sutileza-da-banalizacao-da-graca/" -O licao-02.html
wget "https://escolabiblicadominical.com.br/licao-03-a-sutileza-da-imoralidade-sexual/" -O licao-03.html
wget "https://escolabiblicadominical.com.br/licao-04-a-sutileza-da-normalizacao-do-divorcio/" -O licao-04.html
wget "https://escolabiblicadominical.com.br/licao-05-a-sutileza-do-materialismo-e-do-ateismo/" -O licao-05.html
wget "https://escolabiblicadominical.com.br/licao-06-a-sutileza-das-ideologias-contrarias-a-familia/" -O licao-06.html
wget "https://escolabiblicadominical.com.br/licao-07-a-sutileza-da-relativizacao-da-biblia/" -O licao-07.html
wget "https://escolabiblicadominical.com.br/licao-08-a-sutileza-do-enfraquecimento-da-identidade-pentecostal/" -O licao-08.html
wget "https://escolabiblicadominical.com.br/licao-09-a-sutileza-do-movimento-dos-desigrejados/" -O licao-09.html
wget "https://escolabiblicadominical.com.br/licao-10-a-sutileza-contra-a-pratica-da-mordomia-crista/" -O licao-10.html
wget "https://escolabiblicadominical.com.br/licao-11-a-sutileza-das-midias-sociais/" -O licao-11.html
wget "https://escolabiblicadominical.com.br/licao-12-a-sutileza-da-espiritualidade-holistica/" -O licao-12.html
wget "https://escolabiblicadominical.com.br/licao-13-resistindo-as-sutilezas-de-satanas/" -O licao-13.html
