wget "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiO2ZjLgwtn_jUvX6XMykqyJQI-b25gHqgxus24L4n6gMaF-Fq6XDUtcNLJHQlY5h4w9kKcEyEF1Q1SLxyiwpGK3D8Ucuw6gZlrdBiPppmSWAjq88UHOuUDGAAVMJa1yJB_1nTy-q_7X6xx4EEk9SeQW22nZtBWuuWQ5Q6JeKPbqwZL4z1ibHl4l4J63Q/s16000/nova%20revista%20ebd.png" -o capa.png
wget "https://escolabiblicadominical.com.br/licao-01-as-sutilezas-de-satanas-contra-a-igreja-de-cristo/"
wget "https://escolabiblicadominical.com.br/licao-02-a-sutileza-da-banalizacao-da-graca/"
wget "https://escolabiblicadominical.com.br/licao-03-a-sutileza-da-imoralidade-sexual/"
wget "https://escolabiblicadominical.com.br/licao-04-a-sutileza-da-normalizacao-do-divorcio/"
wget "https://escolabiblicadominical.com.br/licao-05-a-sutileza-do-materialismo-e-do-ateismo/"
wget "https://escolabiblicadominical.com.br/licao-06-a-sutileza-das-ideologias-contrarias-a-familia/"
wget "https://escolabiblicadominical.com.br/licao-07-a-sutileza-da-relativizacao-da-biblia/"
wget "https://escolabiblicadominical.com.br/licao-08-a-sutileza-do-enfraquecimento-da-identidade-pentecostal/"
wget "https://escolabiblicadominical.com.br/licao-09-a-sutileza-do-movimento-dos-desigrejados/"
wget "https://escolabiblicadominical.com.br/licao-10-a-sutileza-contra-a-pratica-da-mordomia-crista/"
wget "https://escolabiblicadominical.com.br/licao-11-a-sutileza-das-midias-sociais/"
wget "https://escolabiblicadominical.com.br/licao-12-a-sutileza-da-espiritualidade-holistica/"
wget "https://escolabiblicadominical.com.br/licao-13-resistindo-as-sutilezas-de-satanas/"
